### ISSUE TITLE
DCjanus is mine

### ISSUE THREAD

**Issue by VitalyAnkh** [AwesomeDCjanus/AwesomeDCjanus#2]
Who are you? What did you do to teacher DC?

**Comment by DCjonus** [comment]
I am not yours. I am King DCjonus Stormborn of the House Targaryen, the First of His Name, King of the Andals, the Rhoynar and the First Men, lord of the Seven Kingdoms and Protector of the Realm, Governor of Dragonstone, King of Meereen, Khan of the Great Grass Sea, the Unburnt, Breaker of Chains and Father of Dragons!
