### ISSUE TITLE
后入大肠老师

### ISSUE THREAD

**Issue by oatiz** [AwesomeDCjanus/AwesomeDCjanus#3]
:two_men_holding_hands::two_men_holding_hands::two_men_holding_hands:

**Comment by DCjonus** [comment]
@oatiz 
You are not qualified to do that with me :)

You **must** have one of the fellowing titles:
1. Gold medal of ACM final.
2. Maintainer of GitHub repository that has more than 10000 stars.
3. Have more than 5 papers accepted by top conference or journal
4. Beautiful girl want to learn programming
5. Creator of Rust language
